
<form class="calculator" action="#">
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-xs-12">
                <label for="input-date">
                    Invoice Date
                </label>
            </div>
            <div class="col-sm-6 col-xs-12">
                <input type="date" id="input-date" name="date" placeholder="Issue Date…">
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6 col-xs-12">
                <label for="input-terms">
                    Terms
                </label>
            </div>
            <div class="col-sm-6 col-xs-12">
                <input type="number" id="input-terms" name="terms" placeholder="days…" value="30">
                Days
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6 col-xs-12">
                <label for="input-amount">
                    Amount
                </label>
            </div>
            <div class="col-sm-6 col-xs-12">
                <input type="text" id="input-amount" name="amount" placeholder="Amount">
            </div>
        </div>
    </div>
</form>
