<?php

declare(strict_types=1);

use App\ViewRenderer;

/** @var ViewRenderer $this */

$this->headTitle('404 Not Found');

?>

<div class="container">
    <h1>Not Found 😩</h1>
    <h2>This is awkward.</h2>
    <p>
        You are looking for something that doesn't exist or may have moved.
        Head back to <a href="<?= $this->url('home') ?>">the late payment calculator here</a>.
    </p>
</div>
