<?php
/**
 * Various Variables used throughout Layout
 */

$companyName = 'netglue';
$legalName   = 'Net Glue Ltd.';

$copyrightFormat = 'Copyright © %1$s %2$s All rights reserved';
$copyrightYear   = 2010;
$copyrightYear   = ($copyrightYear && (int) $copyrightYear < date("Y"))
                 ? sprintf('%d-%d', $copyrightYear, date("Y"))
                 : date("Y");

$copyrightString = sprintf($copyrightFormat, $copyrightYear, $legalName);


?><!DOCTYPE html>
<html lang="en" class="no-js" itemscope itemtype="http://schema.org/WebPage">
<head>
	<meta charset="utf-8">
	<?php echo $this->headTitle(); ?> 
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<?php echo $this->headMeta()->setSeparator("\n\t")."\n"; ?>
    
    <link rel="stylesheet" href="/assets/css/sitewide-33c927f31ffb185197adc14291b08110.css">
    <?php echo $this->headLink()."\n"; ?>
    <?php echo $this->headStyle()."\n"; ?>
    
    
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
    <link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
    <link rel="manifest" href="/manifest.json">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="theme-color" content="#ffffff">
    
    <meta name="twitter:site" content="@netglue">
    <meta name="twitter:creator" content="@netglue">
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:image" content="<?php echo $this->serverUrl('/assets/img/Facebook.png'); ?>">
    <meta name="twitter:url" content="<?php echo $this->serverUrl(); ?>">
    
    <meta property="og:type" content="website">
    <meta property="fb:admins" content="619285782">
    <meta property="og:image" content="<?php echo $this->serverUrl('/assets/img/Facebook.png'); ?>">
    <meta property="og:url" content="<?php echo $this->serverUrl(); ?>">
    
    <meta itemprop="url" content="<?php echo $this->serverUrl(); ?>">
    
</head>
<body>
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-44890297-3', 'auto');
ga('require', 'displayfeatures');
ga('send', 'pageview');
</script>




<div class="site-container">
    <header class="site-header">
        <div class="container">
            <a href="#navigation" class="open-nav"><span class="burger"></span><span class="sr-only">Open Navigation</span></a>
            <div class="brand-header">
                <a href="/">Late Payment<span class="visible-md visible-lg"> Interest</span><span class="visible-sm visible-md visible-lg"> Calculator</span></a>
            </div>
        </div>
    </header>
    <section class="site-body" id="content" itemprop="mainContentOfPage">
        <?php echo $this->content; ?>
    </section>
    <footer class="site-footer">
        <div class="copyright">
            <p>This Late Payment Interest calculator was created by <a href="https://netglue.uk">Net Glue</a> for you to use for free. We hope you find it useful.</p>
            <p>You can find out a bit more <a href="/about">about the calculator here</a>, or <a href="https://netglue.uk/contact">get in touch</a> if you have some feedback
            or suggestions…</p>
            <p><?php echo $this->escapeHtml($copyrightString); ?></p>
            <p>Registered in England &amp; Wales #07190951. VAT Registration #GB 987 3741 64</p>
        </div>
    </footer>
</div>

<div id="navigation" class="mobile-drawer">
    <div class="scroll-container">
        <div class="scroll-wrap">
            <nav class="mobile-nav">
                <?php
                /**
                 * Mobile Navigation
                 */
                ?>
                <div class="container">
                    <div class="row">
                        <ul>
                            <li><a href="/" title="The easiest to use late payment interest calculator on the Internet">Interest Calculator</a></li>
                            <li><a href="/about">About</a></li>
                            <li><a href="https://netglue.uk/contact">Contact</a></li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
    </div>
</div>



<script src="/assets/js/main.min-e6e05d9b887a12441bb7c0cadd3b9b77.js"></script>
<?php echo $this->inlineScript(); ?>
<noscript>
    <div class="no-script">
        <h3>WTF#?!! No Javascript?</h3>
        <p>Sorry, but this late payment calculator won't work without Javascript enabled in
        your browser. Turn it back on and do a refresh and we should be in business!</p>
    </div>
</noscript>
<!--[if lte IE 8]>
<div class="browsehappy" id="browsehappy">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2 alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" data-target="#browsehappy" aria-label="Close"><span class="fa fa-times"></span></button>
                <p class="lead">
                    You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.<br>
                    This website will look simply awful on anything less than Internet Explorer 9
                </p>
                
            </div>
        </div>
    </div>
</div>
<![endif]-->
</body>
</html>
