
name: 'Build Docker Images on Release'

on:
  push:
    tags:
      - '*'
env:
  REGISTRY: ghcr.io

jobs:
  build_and_push:
    name: "Build Images & Push to Registry"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image-name: [php, nginx, cron]
        include:
          - image-name: php
            dockerfile: "php.dockerfile"
          - image-name: nginx
            dockerfile: "nginx.dockerfile"
          - image-name: cron
            dockerfile: "cron.dockerfile"

    env:
      IMAGE_NAME: ${{ github.repository }}-${{ matrix.image-name }}

    steps:
      - name: "Image Name"
        run: echo $IMAGE_NAME

      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Log in to the Container registry"
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Set up Docker Buildx"
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: "Cache Docker layers"
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ env.IMAGE_NAME }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ env.IMAGE_NAME }}

      - name: "Setup Image Meta Data"
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: "Build and push"
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/${{ matrix.dockerfile }}
          builder: ${{ steps.buildx.outputs.name }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
