name: "Deploy"

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      DEPLOY_WEBHOOKS:
        required: true

env:
  WEBHOOKS: ${{ secrets.DEPLOY_WEBHOOKS }}

jobs:
  deploy:
    name: "Update Deployed Images"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        key-name: [ nginx, php, cron ]

    steps:
      - name: "Set Hook Value"
        id: get_hook
        run: |
          echo "::set-output name=HOOK_URL::$(jq -n --argjson in "$WEBHOOKS" -cr '$in | ."${{ matrix.key-name }}"')"

      - name: "POST Hook"
        if: ${{ steps.get_hook.outputs.HOOK_URL }} != ''
        run: |
          curl --fail --request POST --url "${{ steps.get_hook.outputs.HOOK_URL }}"
